- name: Check if required variables are defined
  fail:
    msg: 'variable {{item}} not defined or empty'
  when: (item is undefined) or (item is none) or (item | trim == '')
  with_items:
    - owncloud_db_user
    - owncloud_db_database
    - owncloud_db_password
    - owncloud_db_hostname
    - owncloud_http_dir
    - owncloud_http_user
    - owncloud_http_password
    - owncloud_data_dir


- name: Install owncloud repository
  yum_repository:
    name: owncloud
    description: ownCloud Server
    file: owncloud
    baseurl: http://download.owncloud.org/download/repositories/production/CentOS_7
    gpgkey: http://download.owncloud.org/download/repositories/production/CentOS_7/repodata/repomd.xml.key
    gpgcheck: yes
    enabled: yes

- name: Install remi-php72 repository
  yum_repository:
    name: remi-php72
    description: "Remi's PHP 7.2 RPM"
    file: remi
    baseurl: http://rpms.remirepo.net/enterprise/7/php72/x86_64/
    gpgkey: https://rpms.remirepo.net/RPM-GPG-KEY-remi
    gpgcheck: yes
    enabled: yes

- name: Install remi-safe repository
  yum_repository:
    name: remi-safe
    description: "Remi's safe RPM"
    file: remi
    baseurl: http://rpms.remirepo.net/enterprise/7/safe/x86_64/
    gpgkey: https://rpms.remirepo.net/RPM-GPG-KEY-remi
    gpgcheck: yes
    enabled: yes

- name: install required packages
  yum: 
    name: owncloud-files, httpd, php, php-mysql, mariadb, sqlite, php-dom, php-json, php-xml, php-zip, php-curl, php-mcrypt, php-pear, php-intl, php-mbstring, php-gd, php-pdo, php-process, wget, bzip2, mod_ssl, openssl, rsync
    state: present

- name: Create or resize application volume group
  lvg:
    vg: appvg
    pvs: /dev/sdb

- name: Create or resize a http logical volume
  lvol:
    vg: appvg
    lv: httplv
    size: 20%VG

- name: Create ext3 filesystem for http
  filesystem:
    fstype: ext3
    dev: /dev/mapper/appvg-httplv

- name: Mount http filesystem
  mount:
    path: "{{ owncloud_http_dir }}"
    src: /dev/mapper/appvg-httplv
    fstype: ext3
    opts: defaults
    state: mounted

- name: Create or resize a data logical volume
  lvol:
    vg: appvg
    lv: datalv
    size: 79%VG

- name: Create ext3 filesystem for data
  filesystem:
    fstype: ext3
    dev: /dev/mapper/appvg-datalv

- name: Mount data filesystem
  mount:
    path: "{{ owncloud_data_dir }}"
    src: /dev/mapper/appvg-datalv
    fstype: ext3
    opts: defaults
    state: mounted

- name: Check if the old application directory exist
  stat:
    path: "/var/www/html/owncloud"
  register: exist_result

- name: Copy application data on final directory
  synchronize:
    src: "/var/www/html/owncloud/"
    dest: "{{ owncloud_http_dir }}"
  delegate_to: "{{ inventory_hostname }}"
  when: exist_result.stat.exists and exist_result.stat.isdir

- name: Remove old application directory
  file: path="/var/www/html/owncloud/" state=absent
  when: exist_result.stat.exists and exist_result.stat.isdir

- name: Create link in old application directory
  file:
    src: "{{ owncloud_http_dir }}"
    dest: "/var/www/html/owncloud"
    owner: apache
    group: apache
    state: link
    force: yes

- name: Deploy http configuration template
  template:
    src: owncloud.j2
    dest: /etc/httpd/conf.d/owncloud.conf

- name: remove welcome.conf http file
  file: 
    path: /etc/httpd/conf.d/welcome.conf
    state: absent

- name: Add http port on firewalld
  firewalld:
    service: http
    permanent: true
    immediate: true
    state: enabled

- name: Add https port on firewalld
  firewalld:
    service: https
    permanent: true
    immediate: true
    state: enabled

- name: Add http rigth to connect to the database throw the network
  seboolean:
    name: httpd_can_network_connect_db
    state: yes
    persistent: yes

- name: Add SE right to http directory
  shell: chcon -R -t httpd_sys_rw_content_t "{{ item }}"
  with_items:
    - "{{ owncloud_http_dir }}/"
    - "{{ owncloud_data_dir }}/"

- name: Set UNIX rights on data directory
  file:
    path: "{{ owncloud_data_dir }}"
    owner: apache
    group: apache
    mode: 0755


- name: Configure owncloud
  shell: /usr/bin/php occ maintenance:install --database mysql --database-host {{ owncloud_db_hostname }} --database-name {{ owncloud_db_database }} --database-user {{ owncloud_db_user }} --database-pass {{ owncloud_db_password }} --data-dir {{ owncloud_data_dir }}  --admin-user {{ owncloud_http_user }} --admin-pass {{ owncloud_http_password }}
  args:
    chdir: "{{ owncloud_http_dir }}/"
  become: true
  become_user: apache

- name: Restart service httpd
  service:
    name: httpd
    state: restarted